# nixpacks.toml

[phases.setup]
# Corrected the OpenGL library package name
aptPkgs = [
    "build-essential",
    "pkg-config",
    "tesseract-ocr",
    "poppler-utils",
    "libgl1",  # Corrected package name
    "libglib2.0-0",
    "libsm6",
    "libxext6",
    "libxrender-dev"
]
nixPkgs = ["...", "python311"]

[phases.install]
cmds = [
    "pip install --upgrade pip setuptools wheel",
    "pip install -r requirements.txt"
]

[phases.start]
start_cmd = "gunicorn app:app"

[variables]
PORT = "5000"
