# nixpacks.toml

[phases.setup]
# Add essential build tools and system libraries
# This now includes a more comprehensive list for libraries like OpenCV
aptPkgs = [
    "build-essential",
    "pkg-config",
    "tesseract-ocr",
    "poppler-utils",
    "libgl1-mesa-glx",
    "libglib2.0-0",
    "libsm6",
    "libxext6",
    "libxrender-dev"
]
nixPkgs = ["...", "python311"]

[phases.install]
cmds = [
    "pip install --upgrade pip setuptools wheel",
    "pip install -r requirements.txt"
]

[phases.start]
# Ensure the application starts with the correct command
start_cmd = "gunicorn app:app"

[variables]
# Set the port for the application
PORT = "5000"
