[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "tesseract", "poppler_utils", "pkg-config"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT app:app"

